tag:
  - melabench_zeroshot
  - melabench_fewshot
task: maltese_news_categories
dataset_path: MLRS/maltese_news_categories
dataset_kwargs:
  trust_remote_code: true
  cache_dir: hf-cache
training_split: train
validation_split: validation
test_split: test
fewshot_config:
  sampler: first_n
output_type: multiple_choice
doc_to_text: "{{text}}\n\nWhat are the topic(s) of this news article?"
doc_to_choice: !function choices.choices
doc_to_target: !function choices.choice
metric_list:
  - metric: loglikelihood
    aggregation: !function ../metrics.multilabel_macro_f1
    higher_is_better: true
metadata:
  version: 1.0_english
