tag:
  - melabench_zeroshot
  - melabench_fewshot
task: sentiment_mlt
dataset_path: csv
dataset_kwargs:
  cache_dir: hf-cache
  data_files:
    train: https://raw.githubusercontent.com/jerbarnes/typology_of_crosslingual/master/data/sentiment/mt/train.csv
    validation: https://raw.githubusercontent.com/jerbarnes/typology_of_crosslingual/master/data/sentiment/mt/dev.csv
    test: https://raw.githubusercontent.com/jerbarnes/typology_of_crosslingual/master/data/sentiment/mt/test.csv
  names: ["label", "text"]
training_split: train
validation_split: validation
test_split: test
fewshot_config:
  sampler: first_n
output_type: multiple_choice
doc_to_text: "{{text}}\nIs the sentiment positive or negative?"
doc_to_choice: ["negative", "positive"]
doc_to_target: "{{label}}"
metric_list:
  - metric: f1
    aggregation: !function ../metrics.macro_f1
    higher_is_better: true
metadata:
  version: 1.0_english
