tag:
  - melabench_zeroshot
  - melabench_fewshot
task: flores200_mlt-eng
dataset_path: Muennighoff/flores200
dataset_name: mlt_Latn-eng_Latn
dataset_kwargs:
  trust_remote_code: true
  cache_dir: hf-cache
validation_split: dev
test_split: devtest
output_type: generate_until
doc_to_text: "\"{{sentence_mlt_Latn}}\"\n\nThe previous text is in Maltese. Here is a translation to English:"
doc_to_target: "{{sentence_eng_Latn}}"
metric_list:
  - metric: bleu
    aggregation: bleu
    higher_is_better: true
  - metric: chrf
    aggregation: chrf
    higher_is_better: true
metadata:
  version: 1.0_english
