tag:
  - melabench_zeroshot
  - melabench_fewshot
task: eurlexsum_mlt
dataset_path: dennlinger/eur-lex-sum
dataset_name: maltese
dataset_kwargs:
  trust_remote_code: true
  cache_dir: hf-cache
training_split: train
validation_split: validation
test_split: test
fewshot_config:
  sampler: first_n
output_type: generate_until
doc_to_text: "{{reference}}\n\nWrite a summary in Maltese for the text above:"
doc_to_target: "{{summary}}"
metric_list:
  - metric: bleu
    aggregation: bleu
    higher_is_better: true
  - metric: chrf
    aggregation: chrf
    higher_is_better: true
  - metric: !function ../metrics.rouge
    aggregation: !function ../metrics.rougeL
    higher_is_better: true
generation_kwargs:
  until:
    - "\n"
  do_sample: false
  temperature: 0.0
metadata:
  version: 1.0_english
