tag:
  - zero_shot
  - few_shot
task: opus100_mt-en
dataset_path: MLRS/OPUS-MT-EN-Fixed
dataset_kwargs:
  trust_remote_code: true
  cache_dir: hf-cache
training_split: train
validation_split: validation
test_split: test
output_type: generate_until
doc_to_text: "{{mt}}\n\nThe previous text is in Maltese. Here is a translation to English:"
doc_to_target: "{{en}}"
metric_list:
  - metric: bleu
    aggregation: bleu
    higher_is_better: true
  - metric: chrf
    aggregation: chrf
    higher_is_better: true
