tag:
  - zero_shot
  - few_shot
task: sib200
dataset_path: Davlan/sib200
dataset_name: mlt_Latn
dataset_kwargs:
  trust_remote_code: true
  cache_dir: hf-cache
training_split: train
validation_split: validation
test_split: test
fewshot_config:
  sampler: first_n
output_type: multiple_choice
doc_to_text: "The topic of the news \"{{text}}\" is "
doc_to_choice: ["science/technology", "travel", "politics", "sports", "health", "entertainment", "geography"]
doc_to_target: "{{category}}"
metric_list:
  - metric: acc
    aggregation: mean
    higher_is_better: true
  - metric: f1
    aggregation: !function ../metrics.macro_f1
    higher_is_better: true
