tag:
  - zero_shot
  - few_shot
task: flores200_en-mt
dataset_path: Muennighoff/flores200
dataset_name: eng_Latn-mlt_Latn
dataset_kwargs:
  trust_remote_code: true
  cache_dir: hf-cache
validation_split: dev
test_split: devtest
output_type: generate_until
doc_to_text: "\"{{sentence_eng_Latn}}\"\n\nThe previous text is in English. Here is a translation to Maltese:"
doc_to_target: "{{sentence_mlt_Latn}}"
metric_list:
  - metric: bleu
    aggregation: bleu
    higher_is_better: true
  - metric: chrf
    aggregation: chrf
    higher_is_better: true
