tag:
  - melabench_zeroshot
  - melabench_fewshot
task: opus100_eng-mlt
dataset_path: MLRS/OPUS-MT-EN-Fixed
dataset_kwargs:
  trust_remote_code: true
  cache_dir: hf-cache
training_split: train
validation_split: validation
test_split: test
output_type: generate_until
doc_to_text: "{{en}}\n\nThe previous text is in English. Here is a translation to Maltese:"
doc_to_target: "{{mt}}"
metric_list:
  - metric: bleu
    aggregation: bleu
    higher_is_better: true
  - metric: chrf
    aggregation: chrf
    higher_is_better: true
metadata:
  version: 1.0_english
