tag:
  - zero_shot
  - few_shot
task: sentiment
dataset_path: csv
dataset_kwargs:
  cache_dir: hf-cache
  data_files:
    train: data/Maltese Sentiment/train.csv
    validation: data/Maltese Sentiment/dev.csv
    test: data/Maltese Sentiment/test.csv
  names: ["label", "text"]
training_split: train
validation_split: validation
test_split: test
fewshot_config:
  sampler: first_n
output_type: multiple_choice
doc_to_text: "{{text}}\nIs the sentiment positive or negative?"
doc_to_choice: ["negative", "positive"]
doc_to_target: "{{label}}"
metric_list:
  - metric: f1
    aggregation: !function ../metrics.macro_f1
    higher_is_better: true
