tag:
  - zero_shot
  - few_shot
task: webnlg
dataset_path: tasks/webnlg/webnlg.py
dataset_name: mt
dataset_kwargs:
  data_files:
    train: "data/WebNLG/mt_train.xml"
    validation: "data/WebNLG/mt_dev.xml"
    test: "data/WebNLG/mt_test.xml"
  trust_remote_code: true
  cache_dir: hf-cache
training_split: train
validation_split: validation
test_split: validation
fewshot_config:
  sampler: first_n
output_type: generate_until
doc_to_text: "Verbalize in Maltese the following triples separated by a comma in Maltese: {{modified_triple_sets.mtriple_set[0] | join(', ')}}"
doc_to_target: "{{lex.text[0]}}"
metric_list:
  - metric: bleu
    aggregation: bleu
    higher_is_better: true
  - metric: chrf
    aggregation: chrf
    higher_is_better: true
  - metric: ter
    aggregation: ter
    higher_is_better: false
  - metric: !function ../metrics.rouge
    aggregation: !function ../metrics.rougeL
    higher_is_better: true
generation_kwargs:
  until:
    - "\n"
  do_sample: false
  temperature: 0.0
